export const tabs = [
  {
    key: "dimensions",
    name: "Dimensions",
    nameKey: "navigation.dimensions",
    hideAt: 2.9,
    id: 0,
    hidable: true,
    subtabs: [
      {
        key: "antimatter",
        name: () => `${player.universes.current === 2 ? "Matter" : "Antimatter"} Dimensions`,
        nameKey: "navigation.dimensions.antimatter",
        nameValues: () => ({ resource: player.universes.current === 2 ? "matter" : "antimatter" }),
        symbol: "Ω",
        component: "AntimatterDimensionsTab",
        id: 0,
        hidable: true,
      },
      {
        key: "infinity",
        name: "Infinity Dimensions",
        nameKey: "navigation.dimensions.infinity",
        hideAt: 2.7,
        symbol: "∞",
        component: "InfinityDimensionsTab",
        condition: () =>
          PlayerProgress.endgameUnlocked() ||
          PlayerProgress.realityUnlocked() ||
          PlayerProgress.eternityUnlocked() ||
          InfinityDimension(1).isUnlocked,
        id: 1,
        hidable: true,
      },
      {
        key: "time",
        name: "Time Dimensions",
        nameKey: "navigation.dimensions.time",
        hideAt: 2.6,
        symbol: "Δ",
        component: "TimeDimensionsTab",
        condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.eternityUnlocked(),
        id: 2,
        hidable: true,
      },
      {
        key: "celestial",
        name: "Celestial Dimensions",
        nameKey: "navigation.dimensions.celestial",
        hideAt: 2.5,
        symbol: "✯",
        component: "CelestialDimensionsTab",
        condition: () => PlayerProgress.endgameUnlocked(),
        id: 3,
        hidable: true,
      },
      {
        key: "divine",
        name: "Divine Dimensions",
        nameKey: "navigation.dimensions.divine",
        hideAt: 2.5,
        symbol: "<i class='fas fa-crown'></i>",
        component: "DivineDimensionsTab",
        condition: () => DivinityMilestone.divineDimensions.isReached,
        id: 4,
        hidable: true,
      },
    ]
  },
  {
    key: "options",
    name: "Options",
    nameKey: "tabs.options.name",
    hideAt: 1.6,
    id: 1,
    hidable: false,
    subtabs: [
      {
        key: "saving",
        name: "Saving",
        nameKey: "tabs.options.saving",
        symbol: "<i class='fas fa-save'></i>",
        component: "OptionsSavingTab",
        id: 0,
        hidable: false,
      },
      {
        key: "visual",
        name: "Visual",
        nameKey: "tabs.options.visual",
        symbol: "<i class='fas fa-palette'></i>",
        component: "OptionsVisualTab",
        id: 1,
        hidable: false,
      },
      {
        key: "gameplay",
        name: "Gameplay",
        nameKey: "tabs.options.gameplay",
        symbol: "<i class='fas fa-wrench'></i>",
        component: "OptionsGameplayTab",
        id: 2,
        hidable: false,
      }
    ]
  },
  {
    key: "statistics",
    name: "Statistics",
    nameKey: "navigation.statistics",
    hideAt: 1.7,
    id: 2,
    hidable: true,
    subtabs: [
      {
        key: "statistics",
        name: "Statistics",
        nameKey: "navigation.statistics.statistics",
        symbol: "<i class='fas fa-clipboard-list'></i>",
        component: "StatisticsTab",
        id: 0,
        hidable: true,
      },
      {
        key: "challenges",
        name: "Challenge records",
        nameKey: "navigation.statistics.challenges",
        symbol: "<i class='fas fa-stopwatch'></i>",
        component: "ChallengeRecordsTab",
        condition: () =>
          PlayerProgress.endgameUnlocked() ||
          PlayerProgress.realityUnlocked() ||
          PlayerProgress.eternityUnlocked() ||
          PlayerProgress.challengeCompleted(),
        id: 1,
        hidable: true,
      },
      {
        key: "prestige runs",
        name: "Past Prestige Runs",
        nameKey: "navigation.statistics.prestige_runs",
        symbol: "<i class='fas fa-list-ol'></i>",
        component: "PastPrestigeRunsTab",
        condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.infinityUnlocked(),
        id: 2,
        hidable: true,
      },
      {
        key: "multipliers",
        name: "Multiplier Breakdown",
        nameKey: "navigation.statistics.multipliers",
        symbol: "<i class='fas fa-calculator'></i>",
        component: "MultiplierBreakdownTab",
        condition: () => PlayerProgress.infinityUnlocked(),
        id: 3,
        hidable: true,
      },
      {
        key: "glyph sets",
        name: "Glyph Set Records",
        nameKey: "navigation.statistics.glyph_sets",
        symbol: "<i class='fas fa-ellipsis-h'></i>",
        component: "GlyphSetRecordsTab",
        condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.realityUnlocked(),
        id: 4,
        hidable: true,
      },
      {
        key: "speedrun milestones",
        name: "Speedrun Milestones",
        nameKey: "navigation.statistics.speedrun_milestones",
        symbol: "<i class='fas fa-flag-checkered'></i>",
        component: "SpeedrunMilestonesTab",
        condition: () => player.speedrun.isActive,
        id: 5,
        hidable: true,
      },
      {
        key: "speedrun records",
        name: "Speedrun Records",
        nameKey: "navigation.statistics.speedrun_records",
        symbol: "<i class='fas fa-ranking-star'></i>",
        component: "PreviousSpeedrunTab",
        condition: () => Object.keys(player.speedrun.previousRuns).length > 0,
        id: 6,
        hidable: true,
      },
      {
        key: "stored time",
        name: "Stored Time",
        nameKey: "navigation.statistics.stored_time",
        symbol: "<i class='fas fa-clock'></i>",
        component: "StoredTimeTab",
        id: 7,
        hidable: true,
      },
    ]
  },
  {
    key: "achievements",
    name: "Achievements",
    nameKey: "navigation.achievements",
    hideAt: 1.9,
    id: 3,
    hidable: true,
    subtabs: [
      {
        key: "normal",
        name: "Achievements",
        nameKey: "navigation.achievements.normal",
        symbol: "<i class='fas fa-trophy'></i>",
        component: "NormalAchievementsTab",
        id: 0,
        hidable: true,
      },
      {
        key: "secret",
        name: "Secret Achievements",
        nameKey: "navigation.achievements.secret",
        symbol: "<i class='fas fa-question'></i>",
        component: "SecretAchievementTab",
        id: 1,
        hidable: true,
      }
    ]
  },
  {
    key: "automation",
    name: "Automation",
    nameKey: "navigation.automation",
    id: 4,
    hideAt: 2.1,
    condition: () => PlayerProgress.endgameUnlocked() || player.records.totalAntimatter.gte(1e40),
    hidable: true,
    subtabs: [
      {
        key: "autobuyers",
        name: "Autobuyers",
        nameKey: "navigation.automation.autobuyers",
        symbol: "<i class='fas fa-cog'></i>",
        component: "AutobuyersTab",
        id: 0,
        hidable: true,
      },
      {
        key: "automator",
        name: "Automator",
        nameKey: "navigation.automation.automator",
        symbol: "<i class='fas fa-code'></i>",
        component: "AutomatorTab",
        condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.realityUnlocked(),
        id: 1,
        hidable: true,
      },
    ]
  },
  {
    key: "challenges",
    name: "Challenges",
    nameKey: "navigation.challenges",
    hideAt: 2,
    condition: () =>
      PlayerProgress.endgameUnlocked() ||
      PlayerProgress.realityUnlocked() ||
      PlayerProgress.eternityUnlocked() ||
      PlayerProgress.infinityUnlocked(),
    id: 5,
    hidable: true,
    subtabs: [
      {
        key: "normal",
        name: "Challenges",
        nameKey: "navigation.challenges.normal",
        symbol: "Ω",
        component: "NormalChallengesTab",
        id: 0,
        hidable: true
      },
      {
        key: "infinity",
        name: "Infinity Challenges",
        nameKey: "navigation.challenges.infinity",
        symbol: "∞",
        component: "infinity-challenges-tab",
        condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.realityUnlocked() || PlayerProgress.hasBroken() || Pelle.isDoomed,
        id: 1,
        hidable: true
      },
      {
        key: "eternity",
        name: "Eternity Challenges",
        nameKey: "navigation.challenges.eternity",
        symbol: "Δ",
        component: "eternity-challenges-tab",
        condition: () =>
          PlayerProgress.endgameUnlocked() ||
          PlayerProgress.realityUnlocked() ||
          player.challenge.eternity.unlocked !== 0 ||
          EternityChallenges.all.some(ec => ec.completions > 0),
        id: 2,
        hidable: true
      }
    ],
  },
  {
    key: "infinity",
    name: "Infinity",
    nameKey: "navigation.infinity",
    hideAt: 2.2,
    UIClass: "o-tab-btn--infinity",
    before: "InfinityPointsHeader",
    id: 6,
    condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.infinityUnlocked(),
    hidable: true,
    subtabs: [
      {
        key: "upgrades",
        name: "Infinity Upgrades",
        nameKey: "navigation.infinity.upgrades",
        symbol: "<i class='fas fa-arrow-up'></i>",
        component: "InfinityUpgradesTab",
        condition: () =>
          PlayerProgress.endgameUnlocked() ||
          PlayerProgress.realityUnlocked() ||
          PlayerProgress.eternityUnlocked() ||
          PlayerProgress.infinityUnlocked(),
        id: 0,
        hidable: true,
      },
      {
        key: "break",
        name: "Break Infinity",
        nameKey: "navigation.infinity.break",
        symbol: "∝",
        component: "BreakInfinityTab",
        condition: () =>
          PlayerProgress.endgameUnlocked() ||
          PlayerProgress.realityUnlocked() ||
          PlayerProgress.eternityUnlocked() ||
          PlayerProgress.infinityUnlocked(),
        id: 1,
        hidable: true,
      },
      {
        key: "replicanti",
        name: "Replicanti",
        nameKey: "navigation.infinity.replicanti",
        symbol: "Ξ",
        component: "ReplicantiTab",
        condition: () =>
          PlayerProgress.endgameUnlocked() ||
          PlayerProgress.realityUnlocked() ||
          PlayerProgress.eternityUnlocked() ||
          PlayerProgress.infinityUnlocked(),
        id: 2,
        hidable: true,
      }
    ],
  },
  {
    key: "eternity",
    name: "Eternity",
    nameKey: "navigation.eternity",
    hideAt: 1.8,
    UIClass: "o-tab-btn--eternity",
    condition: () =>
      PlayerProgress.endgameUnlocked() ||
      PlayerProgress.realityUnlocked() ||
      PlayerProgress.eternityUnlocked(),
    before: "EternityPointsHeader",
    id: 7,
    hidable: true,
    subtabs: [
      {
        key: "studies",
        name: "Time Studies",
        nameKey: "navigation.eternity.studies",
        symbol: "<i class='fas fa-book'></i>",
        component: "TimeStudiesTab",
        id: 0,
        hidable: true,
      },
      {
        key: "upgrades",
        name: "Eternity Upgrades",
        nameKey: "navigation.eternity.upgrades",
        symbol: "<i class='fas fa-arrow-up'></i>",
        component: "EternityUpgradesTab",
        id: 1,
        hidable: true,
      },
      {
        key: "milestones",
        name: "Eternity Milestones",
        nameKey: "navigation.eternity.milestones",
        symbol: "<i class='fas fa-star'></i>",
        component: "EternityMilestonesTab",
        id: 2,
        hidable: true,
      },
      {
        key: "dilation",
        name: "Time Dilation",
        nameKey: "navigation.eternity.dilation",
        symbol: "Ψ",
        component: "TimeDilationTab",
        condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.dilationUnlocked() || PlayerProgress.realityUnlocked(),
        id: 3,
        hidable: true,
      }
    ],
  },
  {
    key: "reality",
    name: "Reality",
    nameKey: "navigation.reality",
    hideAt: 2.3,
    UIClass: "o-tab-btn--reality",
    condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.realityUnlocked() || TimeStudy.reality.isBought,
    id: 8,
    hidable: true,
    subtabs: [
      {
        key: "glyphs",
        name: "Glyphs",
        nameKey: "navigation.reality.glyphs",
        symbol: "<i class='fas fa-clone'></i>",
        component: "GlyphsTab",
        id: 0,
        hidable: true,
      },
      {
        key: "upgrades",
        name: "Reality Upgrades",
        nameKey: "navigation.reality.upgrades",
        symbol: "<i class='fas fa-arrow-up'></i>",
        component: "RealityUpgradesTab",
        id: 1,
        hidable: true,
      },
      {
        key: "imag_upgrades",
        name: "Imaginary Upgrades",
        nameKey: "navigation.reality.imag_upgrades",
        symbol: "<i class='fas fa-level-up-alt'></i>",
        component: "ImaginaryUpgradesTab",
        condition: () => PlayerProgress.endgameUnlocked() || MachineHandler.isIMUnlocked,
        id: 2,
        hidable: true,
      },
      {
        key: "dual_upgrades",
        name: "Duality Upgrades",
        nameKey: "navigation.reality.dual_upgrades",
        symbol: "<i class='fas fa-arrow-trend-up'></i>",
        component: "DualityUpgradesTab",
        condition: () => MachineHandler.isDMUnlocked,
        id: 3,
        hidable: true,
      },
      {
        key: "perks",
        name: "Perks",
        nameKey: "navigation.reality.perks",
        symbol: "<i class='fas fa-project-diagram'></i>",
        component: "PerksTab",
        id: 4,
        hidable: true,
      },
      {
        key: "hole",
        name: "Black Hole",
        nameKey: "navigation.reality.hole",
        symbol: "<i class='fas fa-circle'></i>",
        component: "BlackHoleTab",
        condition: () => PlayerProgress.endgameUnlocked() || PlayerProgress.realityUnlocked(),
        id: 5,
        hidable: true,
      },
      {
        key: "alchemy",
        name: "Glyph Alchemy",
        nameKey: "navigation.reality.alchemy",
        symbol: "<i class='fas fa-vial'></i>",
        component: "AlchemyTab",
        condition: () => PlayerProgress.endgameUnlocked() || Ra.unlocks.unlockGlyphAlchemy.canBeApplied,
        id: 6,
        hidable: true,
      },
    ],
  },
  {
    key: "celestials",
    name: "Celestials",
    nameKey: "navigation.celestials",
    hideAt: 2.4,
    UIClass: "o-tab-btn--celestial",
    condition: () => PlayerProgress.endgameUnlocked() || Teresa.isUnlocked,
    id: 9,
    hidable: true,
    subtabs: [
      {
        key: "celestial-navigation",
        name: "Celestial Navigation",
        nameKey: "navigation.celestials.celestial-navigation",
        symbol: "<i class='fas fa-map-marked-alt'></i>",
        component: "CelestialNavigationTab",
        id: 0,
        hidable: true,
      },
      {
        key: "teresa",
        name: "Teresa",
        nameKey: "navigation.celestials.teresa",
        symbol: "Ϟ",
        component: "TeresaTab",
        condition: () => Teresa.isUnlocked,
        id: 1,
        hidable: true,
      },
      {
        key: "effarig",
        name: "Effarig",
        nameKey: "navigation.celestials.effarig",
        symbol: "Ϙ",
        component: "EffarigTab",
        condition: () => TeresaUnlocks.effarig.isUnlocked || EndgameMilestone.celestialEarlyUnlock.isReached,
        id: 2,
        hidable: true,
      },
      {
        key: "enslaved",
        name: "The Nameless Ones",
        nameKey: "navigation.celestials.enslaved",
        symbol: "<div class='o-tab-btn--cel3'>\uf0c1</div>",
        component: "EnslavedTab",
        condition: () => EffarigUnlock.eternity.isUnlocked || EndgameMilestone.celestialEarlyUnlock.isReached,
        id: 3,
        hidable: true,
      },
      {
        key: "v",
        name: "V",
        nameKey: "navigation.celestials.v",
        symbol: "⌬",
        component: "VTab",
        condition: () => Achievement(151).isUnlocked || EndgameMilestone.celestialEarlyUnlock.isReached,
        id: 4,
        hidable: true,
      },
      {
        key: "ra",
        name: "Ra",
        nameKey: "navigation.celestials.ra",
        symbol: "<i class='fas fa-sun'></i>",
        component: "RaTab",
        condition: () => VUnlocks.raUnlock.isUnlocked || EndgameMilestone.celestialEarlyUnlock.isReached,
        id: 5,
        hidable: true,
      },
      {
        key: "laitela",
        name: "Lai'tela",
        nameKey: "navigation.celestials.laitela",
        symbol: "ᛝ",
        component: "LaitelaTab",
        condition: () => Laitela.isUnlocked,
        id: 6,
        hidable: true,
      },
      {
        key: "pelle",
        name: "Pelle",
        nameKey: "navigation.celestials.pelle",
        symbol: "♅",
        component: "PelleTab",
        condition: () => Pelle.isUnlocked,
        id: 7,
        hidable: true,
      },
      {
        key: "alpha",
        name: "Alpha",
        nameKey: "navigation.celestials.alpha",
        symbol: "α",
        component: "AlphaTab",
        condition: () => Alpha.isUnlocked,
        id: 8,
        hidable: true,
      },
      {
        key: "slabdrill",
        name: "Slabdrill",
        nameKey: "navigation.celestials.slabdrill",
        symbol: "⁹δ",
        component: "SlabdrillTab",
        condition: () => Slabdrill.isUnlocked,
        id: 9,
        hidable: true,
      }
    ]
  },
  {
    key: "shop",
    name: "Shop",
    nameKey: "navigation.shop",
    newUIClass: "shop",
    hideAt: 1.5,
    condition: () => Cloud.isAvailable,
    id: 10,
    hidable: true,
    subtabs: [
      {
        key: "shop",
        name: "Shop",
        nameKey: "navigation.shop.shop",
        symbol: "$",
        component: "ShopTab",
        id: 0,
        hidable: true
      }
    ]
  },
  {
    key: "endgame",
    name: "Endgame",
    nameKey: "navigation.endgame",
    hideAt: 2.4,
    UIClass: "o-tab-btn--endgame",
    id: 11,
    condition: () => PlayerProgress.endgameUnlocked(),
    hidable: true,
    subtabs: [
      {
        key: "endgame",
        name: "Endgame",
        nameKey: "navigation.endgame.endgame",
        symbol: "∮",
        component: "EndgameTab",
        id: 0,
        hidable: true,
      },
      {
        key: "break-eternity",
        name: "Break Eternity",
        nameKey: "navigation.endgame.break-eternity",
        symbol: "∇",
        component: "BreakEternityTab",
        id: 1,
        hidable: true,
      },
      {
        key: "pelle-destruction",
        name: "Pelle Destruction",
        nameKey: "navigation.endgame.pelle-destruction",
        symbol: "♆",
        component: "PelleDestructionTab",
        id: 2,
        hidable: true,
      },
      {
        key: "expansion-packs",
        name: "Expansion Packs",
        nameKey: "navigation.endgame.expansion-packs",
        symbol: "<i class='fas fa-expand-arrows-alt'></i>",
        component: "ExpansionPacksTab",
        id: 3,
        hidable: true,
      },
      {
        key: "masteries",
        name: "Endgame Masteries",
        nameKey: "navigation.endgame.masteries",
        symbol: "<i class='fas fa-trophy'></i>",
        component: "EndgameMasteriesTab",
        id: 4,
        hidable: true,
      },
      {
        key: "milestones",
        name: "Endgame Milestones",
        nameKey: "navigation.endgame.milestones",
        symbol: "<i class='fas fa-star'></i>",
        component: "EndgameMilestonesTab",
        id: 5,
        hidable: true,
      },
      {
        key: "upgrades",
        name: "Endgame Upgrades",
        nameKey: "navigation.endgame.upgrades",
        symbol: "<i class='fas fa-arrow-up'></i>",
        component: "EndgameUpgradesTab",
        condition: () => EndgameUpgrades.isUnlocked,
        id: 6,
        hidable: true,
      },
      {
        key: "power",
        name: "Galactic Power",
        nameKey: "navigation.endgame.power",
        symbol: "Ω",
        component: "GalacticPowerTab",
        condition: () => GalacticPower.isUnlocked,
        id: 7,
        hidable: true,
      },
      {
        key: "ethereal",
        name: "The Ethereal",
        nameKey: "navigation.endgame.ethereal",
        symbol: "<i class='fas fa-meteor'></i>",
        component: "EtherealTab",
        condition: () => Ethereal.isUnlocked,
        id: 8,
        hidable: true,
      },
      {
        key: "hypercubes",
        name: "Hypercubes",
        nameKey: "navigation.endgame.hypercubes",
        symbol: "<i class='fas fa-cubes'></i>",
        component: "HypercubesTab",
        condition: () => DualityUpgrade(25).isBought,
        id: 9,
        hidable: true,
      },
      {
        key: "collider",
        name: "Large Hadron Collider",
        nameKey: "navigation.endgame.collider",
        symbol: "<i class='fas fa-atom'></i>",
        component: "LargeHadronColliderTab",
        condition: () => ExpansionPack.alphaPack.isBought,
        id: 10,
        hidable: true,
      },
      {
        key: "ascension",
        name: "Ascension",
        nameKey: "navigation.endgame.ascension",
        symbol: "⤴",
        component: "AscensionTab",
        condition: () => Ascension.isUnlocked,
        id: 11,
        hidable: true,
      },
      {
        key: "compression",
        name: "Time Compression",
        nameKey: "navigation.endgame.compression",
        symbol: "<i class='fas fa-down-left-and-up-right-to-center'></i>",
        component: "TimeCompressionTab",
        condition: () => PlayerProgress.compressionUnlocked(),
        id: 12,
        hidable: true,
      }
    ],
  },
  {
    key: "cdexpansion",
    name: "CD Expansion",
    nameKey: "navigation.cdexpansion",
    hideAt: 2.4,
    UIClass: "o-tab-btn--cd-expansion",
    id: 12,
    condition: () => Alpha.isDestroyedForDisplay,
    hidable: true,
    subtabs: [
      {
        key: "celestial-infinity",
        name: "Celestial Infinity Upgrades",
        nameKey: "navigation.cdexpansion.celestial-infinity",
        symbol: "<i class='fas fa-infinity'></i>",
        component: "CelestialInfinityUpgradesTab",
        id: 0,
        hidable: true,
      },
      {
        key: "celestial-break-infinity",
        name: "Celestial Break Infinity",
        nameKey: "navigation.cdexpansion.celestial-break-infinity",
        symbol: "<i class='fab fa-skyatlas'></i>",
        component: "CelestialBreakInfinityTab",
        condition: () => CelestialInfinityUpgrade.all.filter(u => u.isBought).length === CelestialInfinityUpgrade.all.length ||
          PlayerProgress.celestialEternityUnlocked(),
        id: 1,
        hidable: true,
      },
      {
        key: "celestial-eternity",
        name: "Celestial Eternity Upgrades",
        nameKey: "navigation.cdexpansion.celestial-eternity",
        symbol: "<i class='fas fa-hourglass-start'></i>",
        component: "CelestialEternityUpgradesTab",
        condition: () => PlayerProgress.celestialEternityUnlocked(),
        id: 2,
        hidable: true,
      },
      {
        key: "celestial-eternity-plus",
        name: "Celestial Eternity+ Upgrades",
        nameKey: "navigation.cdexpansion.celestial-eternity-plus",
        symbol: "<i class='fas fa-hourglass-end'></i>",
        component: "CelestialEternityPlusUpgradesTab",
        condition: () => Currency.celestialEternityPoints.gte("1e1000"),
        id: 3,
        hidable: true,
      },
    ],
  },
  {
    key: "divinity",
    name: "Divinity",
    nameKey: "navigation.divinity",
    hideAt: 2.4,
    UIClass: "o-tab-btn--divinity",
    id: 13,
    condition: () => player.celestials.pelle.divinities.gt(0),
    hidable: true,
    subtabs: [
      {
        key: "milestones",
        name: "Divinity Milestones",
        nameKey: "navigation.divinity.milestones",
        symbol: "<i class='fas fa-star'></i>",
        component: "DivinityMilestonesTab",
        id: 0,
        hidable: true,
      },
      {
        key: "upgrades",
        name: "Divinity Upgrades",
        nameKey: "navigation.divinity.upgrades",
        symbol: "<i class='fas fa-arrow-up'></i>",
        component: "DivinityUpgradesTab",
        condition: () => DivinityUpgrades.isUnlocked,
        id: 1,
        hidable: true,
      },
      {
        key: "resurgence",
        name: "Resurgence Upgrades",
        nameKey: "navigation.divinity.resurgence",
        symbol: "<i class='fas fa-bolt-lightning'></i>",
        component: "ResurgenceUpgradesTab",
        condition: () => ResurgenceUpgrades.isUnlocked,
        id: 2,
        hidable: true,
      },
    ],
  },
  {
    key: "universes",
    name: "Universes",
    nameKey: "navigation.universes",
    hideAt: 2.4,
    UIClass: () => universesUI(player.universes.current),
    id: 14,
    condition: () => Universes.areUnlocked,
    hidable: true,
    subtabs: [
      {
        key: "transient",
        name: "Transient Universe",
        nameKey: "navigation.universes.transient",
        symbol: "<i class='fas fa-stopwatch-20'></i>",
        component: "TransientUniverseTab",
        condition: () => Universes.isUnlocked(1),
        id: 0,
        hidable: true,
      },
      {
        key: "tangible",
        name: "Tangible Universe",
        nameKey: "navigation.universes.tangible",
        symbol: "℧",
        component: "TangibleUniverseTab",
        condition: () => Universes.isUnlocked(2),
        id: 1,
        hidable: true,
      },
    ],
  }
];
